### ISSUE TITLE
Vuetify-loader problem with laravel 5.6

### ISSUE THREAD

**Issue by Zeqo** [Nothing-Works/mix#6]
Hi,

I have an issue with this package, when using without vuetify-loader everything works fine but when I try to use it with vuetify-loader everything compiles fine but I get error in console  "component is not defined". I'm using vue 2.6.10, vuetify 2.3.14, vuetify-loader 1.6.0 and laravel 5.6 with laravel-mix@5.0.7

webpack.mix.js file:

**let mix = require('laravel-mix');
require('vuetifyjs-mix-extension');
mix.js('resources/assets/js/app.js', 'public/js').vuetify('vuetify-loader')
.sass('resources/assets/sass/app.scss', 'public/css')**

plugins/vuetify.js file:

**import Vue from 'vue'**
**import Vuetify from 'vuetify/lib'**

**Vue.use(Vuetify)**

**const opts = {}**

**export default new Vuetify(opts)**

And in the main app.js file I have added the following:

import vuetify from './plugins/vuetify';

    const app = new Vue({
    el: '#app',
    store,
    components: { App },
    vuetify,
    router});

**Comment by Nothing-Works** [comment]
Hi, `laravel` version does not really matter for the front end. you may need to check this https://vuetifyjs.com/en/features/treeshaking/#limitations it seems to me that the component is not registered right (I am guessing.)

**Comment by Nothing-Works** [comment]
Will close this, for now, feel free to discuss if you have any questions.
